{
  "cells": [
    {
      "cell_type": "code",
      "execution_count": 2,
      "id": "8d5a4439",
      "metadata": {},
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "====================================================================================================\n",
            "Cross-seed match quality vs. null baseline, across k and training scale\n",
            "====================================================================================================\n",
            "    k        tokens   best_sim mean   best_sim median   null mean   null p95    %>=0.7   %>=null p95\n",
            "   64   250,000,000          0.6910            0.7473      0.2962     0.4772     55.5%         77.1%\n",
            "  128   250,000,000          0.5654            0.5947      0.2648     0.4187     39.3%         65.7%\n",
            "  256   250,000,000          0.2236            0.1728      0.1952     0.3594      1.0%         12.6%\n",
            "   64   500,000,000          0.7565            0.8386      0.3221     0.5118     66.5%         81.8%\n",
            "  128   500,000,000          0.6795            0.7569      0.3030     0.4796     56.9%         75.5%\n",
            "  256   500,000,000          0.2484            0.1761      0.2048     0.3922      2.9%         15.0%\n",
            "   64 1,000,000,000          0.7850            0.8750      0.3314     0.5321     72.0%         83.5%\n",
            "  128 1,000,000,000          0.7268            0.8193      0.3188     0.5231     64.5%         77.9%\n",
            "  256 1,000,000,000          0.2700            0.1806      0.2173     0.4759      4.4%         14.3%\n",
            "\n",
            "Saved raw distributions to outputs/similarity_distributions.npz\n",
            "Saved plot to outputs/similarity_distributions.png\n"
          ]
        }
      ],
      "source": [
        "import re\n",
        "import numpy as np\n",
        "import torch\n",
        "import torch.nn as nn\n",
        "import torch.nn.functional as F\n",
        "from pathlib import Path\n",
        "from typing import Dict, List, Tuple\n",
        "\n",
        "CHECKPOINT_DIR = \".\"\n",
        "SEEDS = [42, 256, 1024]\n",
        "KS = [64, 128, 256]\n",
        "TOKEN_COUNTS = [250_000_000, 500_000_000, 1_000_000_000] # check early, mid, and late training\n",
        "N_NULL_SAMPLES = 1000 # number of anchor draws for the corrected max-of-n_candidates null\n",
        "\n",
        "\n",
        "class SparseAutoencoder(nn.Module):\n",
        "    def __init__(self, d_model: int, n_features: int, seed: int):\n",
        "        super().__init__()\n",
        "        torch.manual_seed(seed)\n",
        "        self.d_model = d_model\n",
        "        self.n_features = n_features\n",
        "        self.W_enc = nn.Parameter(torch.randn(d_model, n_features) * 0.01)\n",
        "        self.b_enc = nn.Parameter(torch.zeros(n_features))\n",
        "        self.W_dec = nn.Parameter(torch.randn(n_features, d_model) * 0.01)\n",
        "        self.b_dec = nn.Parameter(torch.zeros(d_model))\n",
        "        with torch.no_grad():\n",
        "            self.W_dec.data = F.normalize(self.W_dec.data, dim=1)\n",
        "\n",
        "\n",
        "def load_sae(path: Path) -> SparseAutoencoder:\n",
        "    ckpt = torch.load(path, map_location=\"cpu\")\n",
        "    cfg = ckpt[\"config\"]\n",
        "    sae = SparseAutoencoder(cfg[\"d_model\"], cfg[\"n_features\"], seed=0)\n",
        "    sae.load_state_dict(ckpt[\"model_state_dict\"])\n",
        "    return sae\n",
        "\n",
        "\n",
        "def compute_best_sim(sae1: SparseAutoencoder, sae2: SparseAutoencoder) -> np.ndarray:\n",
        "    \"\"\"Best cross-seed match similarity per feature (anchor = sae1).\"\"\"\n",
        "    W1 = F.normalize(sae1.W_dec.detach(), dim=1)\n",
        "    W2 = F.normalize(sae2.W_dec.detach(), dim=1)\n",
        "    sim = (W1 @ W2.T)\n",
        "    best_sim, _ = sim.max(dim=1)\n",
        "    return best_sim.numpy()\n",
        "\n",
        "\n",
        "def compute_null_distribution(sae: SparseAutoencoder, n_samples: int, n_candidates: int) -> np.ndarray:\n",
        "    \"\"\"Null distribution for best_sim under the null hypothesis of no shared\n",
        "    structure across seeds: for each of n_samples anchor features, sample\n",
        "    n_candidates random other features from the same SAE and take the max\n",
        "    similarity among them.\n",
        "    \"\"\"\n",
        "    W = F.normalize(sae.W_dec.detach(), dim=1)\n",
        "    n_features = W.shape[0]\n",
        "    n_candidates = min(n_candidates, n_features - 1)\n",
        "    rng = np.random.default_rng(0)\n",
        "\n",
        "    null_best_sims = np.empty(n_samples)\n",
        "    for i in range(n_samples):\n",
        "        anchor_idx = rng.integers(0, n_features)\n",
        "        # sample distinct candidate indices, excluding the anchor itself\n",
        "        candidates = rng.choice(n_features - 1, size=n_candidates, replace=False)\n",
        "        candidates = np.where(candidates >= anchor_idx, candidates + 1, candidates)\n",
        "        sims = (W[anchor_idx] * W[candidates]).sum(dim=1)\n",
        "        null_best_sims[i] = sims.max().item()\n",
        "\n",
        "    return null_best_sims\n",
        "\n",
        "\n",
        "def main():\n",
        "    ckpt_dir = Path(CHECKPOINT_DIR)\n",
        "    results: Dict[Tuple[int, int], dict] = {}\n",
        "\n",
        "    for tokens in TOKEN_COUNTS:\n",
        "        for k in KS:\n",
        "            paths = {\n",
        "                seed: ckpt_dir / f\"seed{seed}_k{k}_tokens{tokens}.pt\"\n",
        "                for seed in SEEDS\n",
        "            }\n",
        "            missing = [s for s, p in paths.items() if not p.exists()]\n",
        "            if missing:\n",
        "                print(f\"k={k}, tokens={tokens:,}: missing checkpoints for seeds {missing}, skipping.\")\n",
        "                continue\n",
        "\n",
        "            saes = {seed: load_sae(p) for seed, p in paths.items()}\n",
        "            anchor_seed = SEEDS[0]\n",
        "            other_seeds = [s for s in SEEDS if s != anchor_seed]\n",
        "\n",
        "            best_sims_all = []\n",
        "            for other in other_seeds:\n",
        "                best_sims_all.append(compute_best_sim(saes[anchor_seed], saes[other]))\n",
        "            best_sim = np.concatenate(best_sims_all)\n",
        "\n",
        "            null_sim = compute_null_distribution(\n",
        "                saes[anchor_seed], N_NULL_SAMPLES, n_candidates=saes[anchor_seed].n_features\n",
        "            )\n",
        "\n",
        "            results[(k, tokens)] = {\n",
        "                \"best_sim\": best_sim,\n",
        "                \"null_sim\": null_sim,\n",
        "                \"best_sim_mean\": best_sim.mean(),\n",
        "                \"best_sim_median\": np.median(best_sim),\n",
        "                \"null_sim_mean\": null_sim.mean(),\n",
        "                \"null_sim_p95\": np.percentile(null_sim, 95),\n",
        "                \"frac_above_theta\": (best_sim >= 0.7).mean(),\n",
        "                \"frac_above_null_p95\": (best_sim >= np.percentile(null_sim, 95)).mean(),\n",
        "            }\n",
        "\n",
        "    print(\"=\" * 100)\n",
        "    print(\"Cross-seed match quality vs. null baseline, across k and training scale\")\n",
        "    print(\"=\" * 100)\n",
        "    header = f\"{'k':>5} {'tokens':>13} {'best_sim mean':>15} {'best_sim median':>17} {'null mean':>11} {'null p95':>10} {'%>=0.7':>9} {'%>=null p95':>13}\"\n",
        "    print(header)\n",
        "    for (k, tokens), r in results.items():\n",
        "        print(f\"{k:>5} {tokens:>13,} {r['best_sim_mean']:>15.4f} {r['best_sim_median']:>17.4f} \"\n",
        "              f\"{r['null_sim_mean']:>11.4f} {r['null_sim_p95']:>10.4f} \"\n",
        "              f\"{100*r['frac_above_theta']:>8.1f}% {100*r['frac_above_null_p95']:>12.1f}%\")\n",
        "\n",
        "    # Save data for plotting / further analysis\n",
        "    Path(\"outputs\").mkdir(exist_ok=True)\n",
        "    np.savez(\n",
        "        \"outputs/similarity_distributions.npz\",\n",
        "        **{f\"best_sim_k{k}_tok{tokens}\": r[\"best_sim\"] for (k, tokens), r in results.items()},\n",
        "        **{f\"null_sim_k{k}_tok{tokens}\": r[\"null_sim\"] for (k, tokens), r in results.items()},\n",
        "    )\n",
        "    print(\"\\nSaved raw distributions to outputs/similarity_distributions.npz\")\n",
        "\n",
        "    # Plot overlaid histograms\n",
        "    try:\n",
        "        import matplotlib\n",
        "        matplotlib.use(\"Agg\")\n",
        "        import matplotlib.pyplot as plt\n",
        "\n",
        "        n_rows = len(TOKEN_COUNTS)\n",
        "        n_cols = len(KS)\n",
        "        fig, axes = plt.subplots(n_rows, n_cols, figsize=(5 * n_cols, 4 * n_rows), sharey=True, squeeze=False)\n",
        "\n",
        "        for row, tokens in enumerate(TOKEN_COUNTS):\n",
        "            for col, k in enumerate(KS):\n",
        "                ax = axes[row][col]\n",
        "                r = results.get((k, tokens))\n",
        "                if r is None:\n",
        "                    ax.set_visible(False)\n",
        "                    continue\n",
        "                ax.hist(r[\"null_sim\"], bins=40, alpha=0.5, density=True, label=\"null (max of n_candidates random)\")\n",
        "                ax.hist(r[\"best_sim\"], bins=40, alpha=0.5, density=True, label=\"best_sim (cross-seed match)\")\n",
        "                ax.axvline(0.7, color=\"red\", linestyle=\"--\", linewidth=1, label=\"theta=0.7\")\n",
        "                ax.set_title(f\"k={k}, {tokens:,} tokens\")\n",
        "                ax.set_xlabel(\"Cosine similarity\")\n",
        "                if col == 0:\n",
        "                    ax.set_ylabel(\"Density\")\n",
        "                ax.legend(fontsize=7)\n",
        "\n",
        "        plt.tight_layout()\n",
        "        plt.savefig(\"outputs/similarity_distributions.png\", dpi=150)\n",
        "        print(\"Saved plot to outputs/similarity_distributions.png\")\n",
        "    except Exception as e:\n",
        "        print(f\"(Skipped plotting: {e})\")\n",
        "\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "    main()"
      ]
    }
  ],
  "metadata": {
    "kernelspec": {
      "display_name": "base",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "codemirror_mode": {
        "name": "ipython",
        "version": 3
      },
      "file_extension": ".py",
      "mimetype": "text/x-python",
      "name": "python",
      "nbconvert_exporter": "python",
      "pygments_lexer": "ipython3",
      "version": "3.11.4"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 5
}
